version: 0.2
phases:
  install:
    commands:
      - echo "foo"
      - export BUCKET=brich-lambda
      - aws cloudformation package --template-file template.yaml --s3-bucket $BUCKET --output-template-file dotnet-outputtemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - dotnet-outputtemplate.yaml
