version: 0.2
phases:
  install:
    commands:
      - sh build.sh --target=Package
      - export BUCKET=brich-lambda
      - aws cloudformation package --template-file dotnet-template.yaml --s3-bucket $BUCKET --output-template-file dotnet-outputtemplate.yaml
artifacts:
  type: zip
  files:
    - dotnet-template.yaml
    - dotnet-outputtemplate.yaml
